### ISSUE TITLE
Vmt hooking 

### ISSUE THREAD

**Issue by sigge200** [smefcc/smefs-Indigo-Remastered#105]
Please add the vmt hooking method that Oneshot used. The issue here is that there is a chans that you Can get detected. Also People Cant do shit so they need help all The Way through. 

Link 1(source) :https://www.unknowncheats.me/forum/cs-go-releases/288515-csgosimple-2-aimbot-skin-changer-vmt-undetected.html

Link 2 : https://www.unknowncheats.me/forum/cs-go-releases/286736-csgosimple-undetected-vmt.html

Thank you! Sry again.

**Comment by thyanie** [comment]
Send a pull request if you really want it.

**Comment by sigge200** [comment]
Ok
