### ISSUE TITLE
//EDIT Crash Fixed

### ISSUE THREAD

**Issue by letty1337** [smefcc/smefs-Indigo-Remastered#106]
//EDIT

Hey Guys!

So I just tried some stuff out and now heres the fix for the crash!

Go to "Hooks.cpp" and go to line 319 - 320 (if (!SoundTable.InitTable(Interfaces::Sound())) return false;).

And now, do it like this.

			//	if (!SoundTable.InitTable(Interfaces::Sound()))
				//	return false;
So that its not visible by the code.
Your Paste shouldwork again!

Greets 👍

**Comment by thyanie** [comment]
That's some next gen fix right there mate.
