### ISSUE TITLE
Bug about Aimbot

### ISSUE THREAD

**Issue by cha222554** [smefcc/smefs-Indigo-Remastered#109]
**Describe the bug**

**To Reproduce**
1. Go to 'aimbotz  open aimbot select aimbone to "Chest"'
2. Click on 'set bot moving speed 5 .'
3. Scroll down to 'wtf'

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Win10
 - Chrome
 - smef indigo 4.5 

**Smartphone (please complete the following information):**
 - iphone8p
 - 11.4
 - safari
 - ???

**Additional context**

aimbots RCS only working on aimbone set "HEAD"
if use any other aimbone like "Chest" the aimbot(RCS) wont follow target moving.

**Comment by M1XT3NZ** [comment]
you cant even describe the bug or tell the expected behavior.. Too hard for you?

**Comment by cha222554** [comment]
fixed myself

**Comment by smefcc** [comment]
Closed project is dead
