### ISSUE TITLE
Tried updating the cheat to the latest game update but still crashing

### ISSUE THREAD

**Issue by Jeimy041** [smefcc/smefs-Indigo-Remastered#117]
So after changing CInput, GetWeapon, and GetWeaponData right after joining a match the game crashes.

This is what VisualStuudio throws me when debugging and joining a match.
![screenshot_3](https://user-images.githubusercontent.com/38838740/50028007-7f6dc600-ffee-11e8-9f42-d4358ab7ba0e.png)
I don´t know where the issue pls help me out.

**Comment by akasarx** [comment]
https://github.com/smefcc/smefs-Indigo-Remastered/pull/118

**Comment by Yell0** [comment]
same

**Comment by akasarx** [comment]
Try my pull request linked above. It will work perfectly.
Otherwise, just comment out 

if (g_pMisc)
g_pMisc->FrameStageNotify(Stage);

in Client.cpp function OnFrameStageNotify
