### ISSUE TITLE
How Can i use the old 3.0 indigo imgui?

### ISSUE THREAD

**Issue by Kelputo** [smefcc/smefs-Indigo-Remastered#153]
i'm new to coding/pasting welll not new but im lazy to learn c++ and i would like to now if it is possible to have the old indigo menu
if someone can help me it would be great
![311fad5644d3ca06548115d6a8a2a722](https://user-images.githubusercontent.com/88636835/128649777-312c7e74-0002-45fe-b356-fd6a9ef2cd51.png)

**Comment by smefpw** [comment]
you would have to go to the 3.x.x version and just copying the imgui styling code
