### ISSUE TITLE
Project build error C1189 

### ISSUE THREAD

**Issue by theshadowbg6511** [smefcc/smefs-Indigo-Remastered#35]
I start build indigo 4.4.1v and get this "Error C1189 #error:  ERROR: You must use a GNU Compiler. "
![default](https://user-images.githubusercontent.com/39214225/39956160-fc70c1e4-55e3-11e8-8540-0b0a3f84726a.PNG)
![1](https://user-images.githubusercontent.com/39214225/39956176-40e28c7c-55e4-11e8-99d0-b4d195cafed4.PNG)

**Comment by thyanie** [comment]
This is your compiler's problem and has nothing to do with this source.
