### ISSUE TITLE
How to fix this error??

### ISSUE THREAD

**Issue by theshadowbg6511** [smefcc/smefs-Indigo-Remastered#38]
![1](https://user-images.githubusercontent.com/39214225/39956394-26768b96-55e8-11e8-9efe-af2dce83b35c.PNG)
![default](https://user-images.githubusercontent.com/39214225/39956395-269501c0-55e8-11e8-9565-f01585957faf.PNG)

**Comment by Jozkah** [comment]
Google it

**Comment by XakerOrden** [comment]
Download the latest version of DirectX SDK
