### ISSUE TITLE
new bug ?

### ISSUE THREAD

**Issue by pCoder3000** [smefcc/smefs-Indigo-Remastered#40]
Severity	Code	Description	Project	File	Line	Suppression State
Error	C1083	Cannot open source file: 'ImGui\imguicolorpicker.cpp': No such file or directory	smef's Indigo	Z:\Coding\smefs-Indigo-Remastered-master\smefs-Indigo-Remastered-master\INDIGO\c1xx	1

**Comment by Jozkah** [comment]
Already fixed , you could fix that small error your slef
