### ISSUE TITLE
Sniper Crosshair not working

### ISSUE THREAD

**Issue by Gaming12846** [smefcc/smefs-Indigo-Remastered#43]
Sniper Crosshair not working

**Comment by Jozkah** [comment]
It works , you need to spoof sv cheats , in order to use it

**Comment by Floraly** [comment]
spoof convars not good idea!

Same thing goes to ingame Radar Hack.

Leads to untrusted ban!

Create your own draw Crosshair its not that hard!

**Comment by thyanie** [comment]
Neither of these cause an Untrusted ban.
If you want you can go ahead and create yourself a sniper crosshair, we won't mind.
@Floraly
