### ISSUE TITLE
cant save configs?

### ISSUE THREAD

**Issue by suream** [smefcc/smefs-Indigo-Remastered#46]
when i try to save a config it crashed the game

**Comment by XakerOrden** [comment]
Try to update the DirectX SDK before 2010 and again compile cheat

**Comment by UIPL3B** [comment]
Be sure to be putting a name in the config line before pressing save. If this doesn't work follow these steps.

Open "Client.cpp" > Go to lines 29-32 > Replace the "\\" with the directory of where you want to save configs and other output files (IE: "C:\\Users\NAME\Desktop\Cheats" be sure it is "C:\\" and not "C:\") > Now go to line 66-68 and do the same, example below:

		[SPOILER]string ConfigDir = BaseDir + "C:\\Users\NAME\Desktop\Cheats" + "*.ini";
		GuiFile = BaseDir + "C:\\Users\NAME\Desktop\Cheats" + "gui.ini";
		CreateDirectoryW(L"C:\\Indigo", NULL); [/SPOILER]

Hopefully this helps out.

**Comment by UIPL3B** [comment]
Be sure to be putting a name in the config line before pressing save. If this doesn't work follow these steps.

Open "Client.cpp" > Go to lines 29-32 > Replace the "`\\`" with the directory of where you want to save configs and other output files (IE: "`C:\\Users\NAME\Desktop\Cheats`" be sure it is `C:\\` and not `C:\` > Now go to line 66-68 and do the same, example below:

```
                string ConfigDir = BaseDir + "C:\\Users\NAME\Desktop\Cheats" + "*.ini";
		GuiFile = BaseDir + "C:\\Users\NAME\Desktop\Cheats" + "gui.ini";
		CreateDirectoryW(L"C:\\Indigo", NULL);
```

Hopefully this helps out.
