### ISSUE TITLE
Cheat crash

### ISSUE THREAD

**Issue by xnooztvFR** [smefcc/smefs-Indigo-Remastered#50]
Your Windows version: **Windows 10**

Your injector (+ injection method): **Seld coded injector + Manual Map**

Current cheat version (any old versions will not be supported!) **4.4.1**

Bug details? Is it important to fix? **Injecting cheat = CSGO Crash / Yes, it's important**

How do you reproduce it (+ video if possible)? **Inject the cheat.. ^^**

**Comment by thyanie** [comment]
Does not crash for me though.
Are you sure your injector is not the cause?

**Comment by xnooztvFR** [comment]
No, it works fine before your update.

**Comment by xnooztvFR** [comment]
Solved, the crash came from "VMProtect"
I do not understand, I used it before formatting my computer..

**Comment by XakerOrden** [comment]
Now, protecting the memory and packaging from ALL protectors kills some functions, turn off the options "Memory protection" and "Pack the output file", compile again and everything will be injected without problems.

**Comment by xnooztvFR** [comment]
Thanks dude, working fine.
