### ISSUE TITLE
Skin Changer work, but you can ONLY change the skin in the config.

### ISSUE THREAD

**Issue by Gaming12846** [smefcc/smefs-Indigo-Remastered#51]
Your Windows version: Windows 10 Pro

Your injector (+ injection method): Rando Injector

Current cheat version (any old versions will not be supported!):  Newest 4.4.1

Bug details? Is it important to fix?: Skin Changer work, but you can ONLY change the skin in the config.  Yes it it important.

How do you reproduce it (+ video if possible)?: Try it out.

**Comment by thyanie** [comment]
Could you report more specifically what happens when you change them in the menu?

**Comment by Riko1337** [comment]
profile changer dont work,invertory chenger crash

**Comment by Gaming12846** [comment]
Because my English is not the best, i make a video.
https://www.youtube.com/watch?v=xwxo2wVj44g

**Comment by XakerOrden** [comment]
I already said that Skin Changer does not work, I was not listened to :-(

**Comment by thyanie** [comment]
Should be fixed now, can you retry and report back?

**Comment by UIPL3B** [comment]
I can confirm it is working now. Although for some reason no ESP settings are working besides sound and chams for me now. Might be a user error. Cheers
