### ISSUE TITLE
Skin change does not work correctly

### ISSUE THREAD

**Issue by XakerOrden** [smefcc/smefs-Indigo-Remastered#53]
On the weapon/knife/gloves immediately added 2 skin that are mixed, and instead of the names "?????????"
(All libraries are installed (shown in video))
https://youtu.be/p2yG_l0r-9w

**Comment by thyanie** [comment]
This issue is caused when your game isn't being run with English language.

**Comment by XakerOrden** [comment]
Will this be somehow corrected? :-(

**Comment by XakerOrden** [comment]
I ran the game in English, the names corrected, but the skin is all smooth with defects

**Comment by XakerOrden** [comment]
I tested the skin and found out that not all skins are defective, yet some of them work correctly

**Comment by Gaming12846** [comment]
At me its work perfect

**Comment by Gaming12846** [comment]
I play on German and its working fine!
