### ISSUE TITLE
protobuf error while compiling smef v.4.4.1

### ISSUE THREAD

**Issue by Seikusu** [smefcc/smefs-Indigo-Remastered#54]
This error protobuf make inventory changer crashed

1>------ Rebuild All started: Project: smef's Indigo, Configuration: Release Win32 ------
1>Aimbot.cpp
1>AntiAim.cpp
1>LagComp.cpp
1>Client.cpp
1>Esp.cpp
1>InventoryChanger.cpp
1>Knifebot.cpp
1>Misc.cpp
1>Radar.cpp
1>DynSkin.cpp
1>Skin.cpp
1>Triggerbot.cpp
1>CSX_Cvar.cpp
1>CSX_Hook.cpp
1>CSX_Log.cpp
1>CSX_Memory.cpp
1>CSX_Utils.cpp
1>Engine.cpp
1>Entity.cpp
1>EventLogs.cpp
1>Hook.cpp
1>NetVar.cpp
1>Offset.cpp
1>Players.cpp
1>Render.cpp
1>Weapon.cpp
1>Gui.cpp
1>imgui.cpp
1>imgui_draw.cpp
1>imgui_impl_dx9.cpp
1>License.cpp
1>Main.cpp
1>base_gcmessages.pb.cc
1>cstrike15_gcmessages.pb.cc
1>econ_gcmessages.pb.cc
1>engine_gcmessages.pb.cc
1>fatdemo.pb.cc
1>gcsdk_gcmessages.pb.cc
1>gcsystemmsgs.pb.cc
1>netmessages.pb.cc
1>network_connection.pb.cc
1>steamdatagram_messages.pb.cc
1>steammessages.pb.cc
1>ReflectiveLoader.cpp
1>CRC.cpp
1>KeyValues.cpp
1>SDK.cpp
1>Sounds.cpp
1>Spoofed.cpp
1>Vector.cpp
1>Vector2D.cpp
1>Vector4D.cpp
1>VMatrix.cpp
1>Settings.cpp
1>   Creating library C:\Users\Nyanko\Downloads\smefs-Indigo-Remastered-master\Release\smef.pw.lib and object C:\Users\Nyanko\Downloads\smefs-Indigo-Remastered-master\Release\smef.pw.exp
1>libprotobuf.lib(descriptor.obj) : warning LNK4099: PDB 'libprotobuf.pdb' was not found with 'libprotobuf.lib(descriptor.obj)' or at 'C:\Users\Nyanko\Downloads\smefs-Indigo-Remastered-master\Release\libprotobuf.pdb'; linking object as if no debug info
1>libprotobuf.lib(descriptor.pb.obj) : warning LNK4099: PDB 'libprotobuf.pdb' was not found with 'libprotobuf.lib(descriptor.pb.obj)' or at 'C:\Users\Nyanko\Downloads\smefs-Indigo-Remastered-master\Release\libprotobuf.pdb'; linking object as if no debug info
1>libprotobuf.lib(descriptor_database.obj) : warning LNK4099: PDB 'libprotobuf.pdb' was not found with 'libprotobuf.lib(descriptor_database.obj)' or at 'C:\Users\Nyanko\Downloads\smefs-Indigo-Remastered-master\Release\libprotobuf.pdb'; linking object as if no debug info
1>libprotobuf.lib(dynamic_message.obj) : warning LNK4099: PDB 'libprotobuf.pdb' was not found with 'libprotobuf.lib(dynamic_message.obj)' or at 'C:\Users\Nyanko\Downloads\smefs-Indigo-Remastered-master\Release\libprotobuf.pdb'; linking object as if no debug info
1>libprotobuf.lib(extension_set.obj) : warning LNK4099: PDB 'libprotobuf.pdb' was not found with 'libprotobuf.lib(extension_set.obj)' or at 'C:\Users\Nyanko\Downloads\smefs-Indigo-Remastered-master\Release\libprotobuf.pdb'; linking object as if no debug info
1>libprotobuf.lib(extension_set_heavy.obj) : warning LNK4099: PDB 'libprotobuf.pdb' was not found with 'libprotobuf.lib(extension_set_heavy.obj)' or at 'C:\Users\Nyanko\Downloads\smefs-Indigo-Remastered-master\Release\libprotobuf.pdb'; linking object as if no debug info
1>libprotobuf.lib(generated_message_reflection.obj) : warning LNK4099: PDB 'libprotobuf.pdb' was not found with 'libprotobuf.lib(generated_message_reflection.obj)' or at 'C:\Users\Nyanko\Downloads\smefs-Indigo-Remastered-master\Release\libprotobuf.pdb'; linking object as if no debug info
1>libprotobuf.lib(generated_message_util.obj) : warning LNK4099: PDB 'libprotobuf.pdb' was not found with 'libprotobuf.lib(generated_message_util.obj)' or at 'C:\Users\Nyanko\Downloads\smefs-Indigo-Remastered-master\Release\libprotobuf.pdb'; linking object as if no debug info
1>libprotobuf.lib(coded_stream.obj) : warning LNK4099: PDB 'libprotobuf.pdb' was not found with 'libprotobuf.lib(coded_stream.obj)' or at 'C:\Users\Nyanko\Downloads\smefs-Indigo-Remastered-master\Release\libprotobuf.pdb'; linking object as if no debug info
1>libprotobuf.lib(tokenizer.obj) : warning LNK4099: PDB 'libprotobuf.pdb' was not found with 'libprotobuf.lib(tokenizer.obj)' or at 'C:\Users\Nyanko\Downloads\smefs-Indigo-Remastered-master\Release\libprotobuf.pdb'; linking object as if no debug info
1>libprotobuf.lib(zero_copy_stream.obj) : warning LNK4099: PDB 'libprotobuf.pdb' was not found with 'libprotobuf.lib(zero_copy_stream.obj)' or at 'C:\Users\Nyanko\Downloads\smefs-Indigo-Remastered-master\Release\libprotobuf.pdb'; linking object as if no debug info
1>libprotobuf.lib(zero_copy_stream_impl.obj) : warning LNK4099: PDB 'libprotobuf.pdb' was not found with 'libprotobuf.lib(zero_copy_stream_impl.obj)' or at 'C:\Users\Nyanko\Downloads\smefs-Indigo-Remastered-master\Release\libprotobuf.pdb'; linking object as if no debug info
1>libprotobuf.lib(zero_copy_stream_impl_lite.obj) : warning LNK4099: PDB 'libprotobuf.pdb' was not found with 'libprotobuf.lib(zero_copy_stream_impl_lite.obj)' or at 'C:\Users\Nyanko\Downloads\smefs-Indigo-Remastered-master\Release\libprotobuf.pdb'; linking object as if no debug info
1>libprotobuf.lib(message.obj) : warning LNK4099: PDB 'libprotobuf.pdb' was not found with 'libprotobuf.lib(message.obj)' or at 'C:\Users\Nyanko\Downloads\smefs-Indigo-Remastered-master\Release\libprotobuf.pdb'; linking object as if no debug info
1>libprotobuf.lib(message_lite.obj) : warning LNK4099: PDB 'libprotobuf.pdb' was not found with 'libprotobuf.lib(message_lite.obj)' or at 'C:\Users\Nyanko\Downloads\smefs-Indigo-Remastered-master\Release\libprotobuf.pdb'; linking object as if no debug info
1>libprotobuf.lib(reflection_ops.obj) : warning LNK4099: PDB 'libprotobuf.pdb' was not found with 'libprotobuf.lib(reflection_ops.obj)' or at 'C:\Users\Nyanko\Downloads\smefs-Indigo-Remastered-master\Release\libprotobuf.pdb'; linking object as if no debug info
1>libprotobuf.lib(repeated_field.obj) : warning LNK4099: PDB 'libprotobuf.pdb' was not found with 'libprotobuf.lib(repeated_field.obj)' or at 'C:\Users\Nyanko\Downloads\smefs-Indigo-Remastered-master\Release\libprotobuf.pdb'; linking object as if no debug info
1>libprotobuf.lib(atomicops_internals_x86_msvc.obj) : warning LNK4099: PDB 'libprotobuf.pdb' was not found with 'libprotobuf.lib(atomicops_internals_x86_msvc.obj)' or at 'C:\Users\Nyanko\Downloads\smefs-Indigo-Remastered-master\Release\libprotobuf.pdb'; linking object as if no debug info
1>libprotobuf.lib(common.obj) : warning LNK4099: PDB 'libprotobuf.pdb' was not found with 'libprotobuf.lib(common.obj)' or at 'C:\Users\Nyanko\Downloads\smefs-Indigo-Remastered-master\Release\libprotobuf.pdb'; linking object as if no debug info
1>libprotobuf.lib(once.obj) : warning LNK4099: PDB 'libprotobuf.pdb' was not found with 'libprotobuf.lib(once.obj)' or at 'C:\Users\Nyanko\Downloads\smefs-Indigo-Remastered-master\Release\libprotobuf.pdb'; linking object as if no debug info
1>libprotobuf.lib(stringprintf.obj) : warning LNK4099: PDB 'libprotobuf.pdb' was not found with 'libprotobuf.lib(stringprintf.obj)' or at 'C:\Users\Nyanko\Downloads\smefs-Indigo-Remastered-master\Release\libprotobuf.pdb'; linking object as if no debug info
1>libprotobuf.lib(structurally_valid.obj) : warning LNK4099: PDB 'libprotobuf.pdb' was not found with 'libprotobuf.lib(structurally_valid.obj)' or at 'C:\Users\Nyanko\Downloads\smefs-Indigo-Remastered-master\Release\libprotobuf.pdb'; linking object as if no debug info
1>libprotobuf.lib(strutil.obj) : warning LNK4099: PDB 'libprotobuf.pdb' was not found with 'libprotobuf.lib(strutil.obj)' or at 'C:\Users\Nyanko\Downloads\smefs-Indigo-Remastered-master\Release\libprotobuf.pdb'; linking object as if no debug info
1>libprotobuf.lib(substitute.obj) : warning LNK4099: PDB 'libprotobuf.pdb' was not found with 'libprotobuf.lib(substitute.obj)' or at 'C:\Users\Nyanko\Downloads\smefs-Indigo-Remastered-master\Release\libprotobuf.pdb'; linking object as if no debug info
1>libprotobuf.lib(text_format.obj) : warning LNK4099: PDB 'libprotobuf.pdb' was not found with 'libprotobuf.lib(text_format.obj)' or at 'C:\Users\Nyanko\Downloads\smefs-Indigo-Remastered-master\Release\libprotobuf.pdb'; linking object as if no debug info
1>libprotobuf.lib(unknown_field_set.obj) : warning LNK4099: PDB 'libprotobuf.pdb' was not found with 'libprotobuf.lib(unknown_field_set.obj)' or at 'C:\Users\Nyanko\Downloads\smefs-Indigo-Remastered-master\Release\libprotobuf.pdb'; linking object as if no debug info
1>libprotobuf.lib(wire_format.obj) : warning LNK4099: PDB 'libprotobuf.pdb' was not found with 'libprotobuf.lib(wire_format.obj)' or at 'C:\Users\Nyanko\Downloads\smefs-Indigo-Remastered-master\Release\libprotobuf.pdb'; linking object as if no debug info
1>libprotobuf.lib(wire_format_lite.obj) : warning LNK4099: PDB 'libprotobuf.pdb' was not found with 'libprotobuf.lib(wire_format_lite.obj)' or at 'C:\Users\Nyanko\Downloads\smefs-Indigo-Remastered-master\Release\libprotobuf.pdb'; linking object as if no debug info
1>INDIGO.vcxproj -> C:\Users\Nyanko\Downloads\smefs-Indigo-Remastered-master\Release\smef.pw.dll
1>Done building project "INDIGO.vcxproj".
========== Rebuild All: 1 succeeded, 0 failed, 0 skipped ==========

**Comment by thyanie** [comment]
These are **NOT ERRORS.**
These are linking warnings when *.pdb files can't be found.
1>INDIGO.vcxproj -> C:\Users\Nyanko\Downloads\smefs-Indigo-Remastered-master\Release\smef.pw.dll
1>Done building project "INDIGO.vcxproj".
========== Rebuild All: 1 succeeded, 0 failed, 0 skipped ==========

**Comment by XakerOrden** [comment]
It's ok, just ignore it.
