### ISSUE TITLE
Crash when saving config

### ISSUE THREAD

**Issue by itsajna** [smefcc/smefs-Indigo-Remastered#56]
Windows 10 V.1709 Here latest Visual Studio and latest source. 
Here's my problem : When compiling i get : "warning LNK4099: PDB 'libprotobuf.pdb'" 👎 
But the DLL sucessfully compile apparently, skin changer seems to open and not crash since latest version💯
But when i save the config in game CS just crashes.

 

(FULL BUILD OUTPUT)
`1>------ Début de la génération : Projet : smef's Indigo, Configuration : Release Win32 ------
1>Aimbot.cpp
1>AntiAim.cpp
1>LagComp.cpp
1>Client.cpp
1>Esp.cpp
1>InventoryChanger.cpp
1>Knifebot.cpp
1>Misc.cpp
1>Radar.cpp
1>DynSkin.cpp
1>Skin.cpp
1>Triggerbot.cpp
1>CSX_Cvar.cpp
1>CSX_Hook.cpp
1>CSX_Log.cpp
1>CSX_Memory.cpp
1>CSX_Utils.cpp
1>Engine.cpp
1>Entity.cpp
1>EventLogs.cpp
1>Hook.cpp
1>NetVar.cpp
1>Offset.cpp
1>Players.cpp
1>Render.cpp
1>Weapon.cpp
1>Gui.cpp
1>imgui.cpp
1>imgui_draw.cpp
1>imgui_impl_dx9.cpp
1>License.cpp
1>Main.cpp
1>base_gcmessages.pb.cc
1>cstrike15_gcmessages.pb.cc
1>econ_gcmessages.pb.cc
1>engine_gcmessages.pb.cc
1>fatdemo.pb.cc
1>gcsdk_gcmessages.pb.cc
1>gcsystemmsgs.pb.cc
1>netmessages.pb.cc
1>network_connection.pb.cc
1>steamdatagram_messages.pb.cc
1>steammessages.pb.cc
1>ReflectiveLoader.cpp
1>CRC.cpp
1>KeyValues.cpp
1>SDK.cpp
1>Sounds.cpp
1>Spoofed.cpp
1>Vector.cpp
1>Vector2D.cpp
1>Vector4D.cpp
1>VMatrix.cpp
1>Settings.cpp
1>   Création de la bibliothèque C:\Users\Ajna\Documents\smefs-Indigo-Remastered-master\Release\smef.pw.lib et de l'objet C:\Users\Ajna\Documents\smefs-Indigo-Remastered-master\Release\smef.pw.exp
1>libprotobuf.lib(descriptor.obj) : warning LNK4099: PDB 'libprotobuf.pdb' n'a pu être trouvé avec 'libprotobuf.lib(descriptor.obj)' ou sur 'C:\Users\Ajna\Documents\smefs-Indigo-Remastered-master\Release\libprotobuf.pdb' ; l'objet sera lié sans informations de débogage
1>libprotobuf.lib(descriptor.pb.obj) : warning LNK4099: PDB 'libprotobuf.pdb' n'a pu être trouvé avec 'libprotobuf.lib(descriptor.pb.obj)' ou sur 'C:\Users\Ajna\Documents\smefs-Indigo-Remastered-master\Release\libprotobuf.pdb' ; l'objet sera lié sans informations de débogage
1>libprotobuf.lib(descriptor_database.obj) : warning LNK4099: PDB 'libprotobuf.pdb' n'a pu être trouvé avec 'libprotobuf.lib(descriptor_database.obj)' ou sur 'C:\Users\Ajna\Documents\smefs-Indigo-Remastered-master\Release\libprotobuf.pdb' ; l'objet sera lié sans informations de débogage
1>libprotobuf.lib(dynamic_message.obj) : warning LNK4099: PDB 'libprotobuf.pdb' n'a pu être trouvé avec 'libprotobuf.lib(dynamic_message.obj)' ou sur 'C:\Users\Ajna\Documents\smefs-Indigo-Remastered-master\Release\libprotobuf.pdb' ; l'objet sera lié sans informations de débogage
1>libprotobuf.lib(extension_set.obj) : warning LNK4099: PDB 'libprotobuf.pdb' n'a pu être trouvé avec 'libprotobuf.lib(extension_set.obj)' ou sur 'C:\Users\Ajna\Documents\smefs-Indigo-Remastered-master\Release\libprotobuf.pdb' ; l'objet sera lié sans informations de débogage
1>libprotobuf.lib(extension_set_heavy.obj) : warning LNK4099: PDB 'libprotobuf.pdb' n'a pu être trouvé avec 'libprotobuf.lib(extension_set_heavy.obj)' ou sur 'C:\Users\Ajna\Documents\smefs-Indigo-Remastered-master\Release\libprotobuf.pdb' ; l'objet sera lié sans informations de débogage
1>libprotobuf.lib(generated_message_reflection.obj) : warning LNK4099: PDB 'libprotobuf.pdb' n'a pu être trouvé avec 'libprotobuf.lib(generated_message_reflection.obj)' ou sur 'C:\Users\Ajna\Documents\smefs-Indigo-Remastered-master\Release\libprotobuf.pdb' ; l'objet sera lié sans informations de débogage
1>libprotobuf.lib(generated_message_util.obj) : warning LNK4099: PDB 'libprotobuf.pdb' n'a pu être trouvé avec 'libprotobuf.lib(generated_message_util.obj)' ou sur 'C:\Users\Ajna\Documents\smefs-Indigo-Remastered-master\Release\libprotobuf.pdb' ; l'objet sera lié sans informations de débogage
1>libprotobuf.lib(coded_stream.obj) : warning LNK4099: PDB 'libprotobuf.pdb' n'a pu être trouvé avec 'libprotobuf.lib(coded_stream.obj)' ou sur 'C:\Users\Ajna\Documents\smefs-Indigo-Remastered-master\Release\libprotobuf.pdb' ; l'objet sera lié sans informations de débogage
1>libprotobuf.lib(tokenizer.obj) : warning LNK4099: PDB 'libprotobuf.pdb' n'a pu être trouvé avec 'libprotobuf.lib(tokenizer.obj)' ou sur 'C:\Users\Ajna\Documents\smefs-Indigo-Remastered-master\Release\libprotobuf.pdb' ; l'objet sera lié sans informations de débogage
1>libprotobuf.lib(zero_copy_stream.obj) : warning LNK4099: PDB 'libprotobuf.pdb' n'a pu être trouvé avec 'libprotobuf.lib(zero_copy_stream.obj)' ou sur 'C:\Users\Ajna\Documents\smefs-Indigo-Remastered-master\Release\libprotobuf.pdb' ; l'objet sera lié sans informations de débogage
1>libprotobuf.lib(zero_copy_stream_impl.obj) : warning LNK4099: PDB 'libprotobuf.pdb' n'a pu être trouvé avec 'libprotobuf.lib(zero_copy_stream_impl.obj)' ou sur 'C:\Users\Ajna\Documents\smefs-Indigo-Remastered-master\Release\libprotobuf.pdb' ; l'objet sera lié sans informations de débogage
1>libprotobuf.lib(zero_copy_stream_impl_lite.obj) : warning LNK4099: PDB 'libprotobuf.pdb' n'a pu être trouvé avec 'libprotobuf.lib(zero_copy_stream_impl_lite.obj)' ou sur 'C:\Users\Ajna\Documents\smefs-Indigo-Remastered-master\Release\libprotobuf.pdb' ; l'objet sera lié sans informations de débogage
1>libprotobuf.lib(message.obj) : warning LNK4099: PDB 'libprotobuf.pdb' n'a pu être trouvé avec 'libprotobuf.lib(message.obj)' ou sur 'C:\Users\Ajna\Documents\smefs-Indigo-Remastered-master\Release\libprotobuf.pdb' ; l'objet sera lié sans informations de débogage
1>libprotobuf.lib(message_lite.obj) : warning LNK4099: PDB 'libprotobuf.pdb' n'a pu être trouvé avec 'libprotobuf.lib(message_lite.obj)' ou sur 'C:\Users\Ajna\Documents\smefs-Indigo-Remastered-master\Release\libprotobuf.pdb' ; l'objet sera lié sans informations de débogage
1>libprotobuf.lib(reflection_ops.obj) : warning LNK4099: PDB 'libprotobuf.pdb' n'a pu être trouvé avec 'libprotobuf.lib(reflection_ops.obj)' ou sur 'C:\Users\Ajna\Documents\smefs-Indigo-Remastered-master\Release\libprotobuf.pdb' ; l'objet sera lié sans informations de débogage
1>libprotobuf.lib(repeated_field.obj) : warning LNK4099: PDB 'libprotobuf.pdb' n'a pu être trouvé avec 'libprotobuf.lib(repeated_field.obj)' ou sur 'C:\Users\Ajna\Documents\smefs-Indigo-Remastered-master\Release\libprotobuf.pdb' ; l'objet sera lié sans informations de débogage
1>libprotobuf.lib(atomicops_internals_x86_msvc.obj) : warning LNK4099: PDB 'libprotobuf.pdb' n'a pu être trouvé avec 'libprotobuf.lib(atomicops_internals_x86_msvc.obj)' ou sur 'C:\Users\Ajna\Documents\smefs-Indigo-Remastered-master\Release\libprotobuf.pdb' ; l'objet sera lié sans informations de débogage
1>libprotobuf.lib(common.obj) : warning LNK4099: PDB 'libprotobuf.pdb' n'a pu être trouvé avec 'libprotobuf.lib(common.obj)' ou sur 'C:\Users\Ajna\Documents\smefs-Indigo-Remastered-master\Release\libprotobuf.pdb' ; l'objet sera lié sans informations de débogage
1>libprotobuf.lib(once.obj) : warning LNK4099: PDB 'libprotobuf.pdb' n'a pu être trouvé avec 'libprotobuf.lib(once.obj)' ou sur 'C:\Users\Ajna\Documents\smefs-Indigo-Remastered-master\Release\libprotobuf.pdb' ; l'objet sera lié sans informations de débogage
1>libprotobuf.lib(stringprintf.obj) : warning LNK4099: PDB 'libprotobuf.pdb' n'a pu être trouvé avec 'libprotobuf.lib(stringprintf.obj)' ou sur 'C:\Users\Ajna\Documents\smefs-Indigo-Remastered-master\Release\libprotobuf.pdb' ; l'objet sera lié sans informations de débogage
1>libprotobuf.lib(structurally_valid.obj) : warning LNK4099: PDB 'libprotobuf.pdb' n'a pu être trouvé avec 'libprotobuf.lib(structurally_valid.obj)' ou sur 'C:\Users\Ajna\Documents\smefs-Indigo-Remastered-master\Release\libprotobuf.pdb' ; l'objet sera lié sans informations de débogage
1>libprotobuf.lib(strutil.obj) : warning LNK4099: PDB 'libprotobuf.pdb' n'a pu être trouvé avec 'libprotobuf.lib(strutil.obj)' ou sur 'C:\Users\Ajna\Documents\smefs-Indigo-Remastered-master\Release\libprotobuf.pdb' ; l'objet sera lié sans informations de débogage
1>libprotobuf.lib(substitute.obj) : warning LNK4099: PDB 'libprotobuf.pdb' n'a pu être trouvé avec 'libprotobuf.lib(substitute.obj)' ou sur 'C:\Users\Ajna\Documents\smefs-Indigo-Remastered-master\Release\libprotobuf.pdb' ; l'objet sera lié sans informations de débogage
1>libprotobuf.lib(text_format.obj) : warning LNK4099: PDB 'libprotobuf.pdb' n'a pu être trouvé avec 'libprotobuf.lib(text_format.obj)' ou sur 'C:\Users\Ajna\Documents\smefs-Indigo-Remastered-master\Release\libprotobuf.pdb' ; l'objet sera lié sans informations de débogage
1>libprotobuf.lib(unknown_field_set.obj) : warning LNK4099: PDB 'libprotobuf.pdb' n'a pu être trouvé avec 'libprotobuf.lib(unknown_field_set.obj)' ou sur 'C:\Users\Ajna\Documents\smefs-Indigo-Remastered-master\Release\libprotobuf.pdb' ; l'objet sera lié sans informations de débogage
1>libprotobuf.lib(wire_format.obj) : warning LNK4099: PDB 'libprotobuf.pdb' n'a pu être trouvé avec 'libprotobuf.lib(wire_format.obj)' ou sur 'C:\Users\Ajna\Documents\smefs-Indigo-Remastered-master\Release\libprotobuf.pdb' ; l'objet sera lié sans informations de débogage
1>libprotobuf.lib(wire_format_lite.obj) : warning LNK4099: PDB 'libprotobuf.pdb' n'a pu être trouvé avec 'libprotobuf.lib(wire_format_lite.obj)' ou sur 'C:\Users\Ajna\Documents\smefs-Indigo-Remastered-master\Release\libprotobuf.pdb' ; l'objet sera lié sans informations de débogage
1>INDIGO.vcxproj -> C:\Users\Ajna\Documents\smefs-Indigo-Remastered-master\Release\smef.pw.dll
1>Génération du projet "INDIGO.vcxproj" terminée.
========== Génération : 1 a réussi, 0 a échoué, 0 mis à jour, 0 a été ignoré ==========
`

**Comment by itsajna** [comment]
Windows 10 Pro N

With an old version of the DLL i still get "Desktop.ini" so it might be because of that but i don't know where to find or remove it

**Comment by UIPL3B** [comment]
I get the same issue but I can't load configs. No matter what it just crashes even after changing all directories in Client.cpp.

**Comment by smefcc** [comment]
Make sure the injector is ran as admin to ensure the cheat has access to save on C::

**Comment by mettsai** [comment]
Getting crash, and yes injector is started as admin. Old versions of Indigo doesn't crash.

**Comment by XakerOrden** [comment]
+Tested, sometimes when saving configs, the game crashes
