### ISSUE TITLE
Why only use English?

### ISSUE THREAD

**Issue by EnderMagic** [smefcc/smefs-Indigo-Remastered#57]
ok
i come from china,so i use chinese
but skinschange name is ???
pls support more language

**Comment by Gaming12846** [comment]
- I can translate the Cheat to German for multi language Support.

**Comment by Cra4ck** [comment]
you need to learn multiple languages
or do you just want to sell it for the paste?

这些英文很基础的好吗 一看就是初中没好好听课

**Comment by XakerOrden** [comment]
I personally do not sell the paste, but the smef source is very good, it's better to update the sources than indigo has not seen, thanks smef.
