### ISSUE TITLE
Config not saving all Features

### ISSUE THREAD

**Issue by Gaming12846** [smefcc/smefs-Indigo-Remastered#58]
Your Windows version: Windows 10 Pro

Your injector (+ injection method): Rando Injector

Current cheat version (any old versions will not be supported!): Newest 4.4.1

Bug details? Is it important to fix?: Config don't save all Features. It is important for me.

How do you reproduce it (+ video if possible)?: Try it out.

**I do a List with all Features their dont save:** 

**Weapon Option:**
-Legit Anti Aim
-Silent Aim
-Draw Backtrack Ticks

**Visuals Part1:**
-Team
-Enemy
-Chicken
-Dynamic Lights
-Watermarks

**Visuals Part3:**
-Chams XQZ
-Chams Materials + Materials
-Arms Materials + Type + Material
-Hitmaker + Sound
-Hitlogs

**Skinchanger:**
-Knife Skins
-Knife Wear
-Weapon Skin
-Weapon Quality
-Weapon Wear
-Weapon Stattrack

**Inventory Changer:**
Don't save anything

**Profile Changer**
Don't save anything

**Misc:**
-Inventory Unlocker
-Chat Spam
-Random Chat Spam
-Static Name Spam
-Clantag Changer

**Untrusted Features:**
-Enable Untrusted Features
-No Sky
-Third Person + Range
-SkyBox

**Config:**
-Menu Color

**Colors:**
-Dynamic Lights Color

**Comment by thyanie** [comment]
Some of these features are **intentionally** not saved to ensure safety.
I'll make some of these save when I have time.

**Comment by IntenceYT** [comment]
I don't see why you should care about not saving features for safety.
It's user fault if they activate something which could cause a VAC/SMAC/Untrusted ban and it's annoying for people who wants these features to be activated at start.

**Comment by XakerOrden** [comment]
+ I completely agree, a person should think for himself and not others for him, make complete saving of configs.
