### ISSUE TITLE
LegitAA causes demos to flicker

### ISSUE THREAD

**Issue by flatCS** [smefcc/smefs-Indigo-Remastered#61]
Your Windows version - Windows 10 Home 1709

Your injector (+ injection method) - Rando

Current cheat version (any old versions will not be supported!) - 4.4.1

Bug details? Is it important to fix? - Injected an unchanged build with -insecure flag. Didn't really want to check if OW demos were any different, risking a ban. When I tried to replay a demo recorded on a comp map, my game straight went to <1fps (both injected and uninjected).

How do you reproduce it (+ video if possible)? - https://www.youtube.com/watch?v=qjJNvsXXTlc Literally just turn on LegitAA, record a demo and replay it. Video recorded uninjected.

**Comment by smefcc** [comment]
If you used "record xxx" and "play xxx" it flickers with all Legit Anti Aims; Try it with corruption.

If you play a comp then watch the demo back it will not flicker
