### ISSUE TITLE
add

### ISSUE THREAD

**Issue by omarloler** [smefcc/smefs-Indigo-Remastered#69]
Can u add rage bot plz for hvh ?

**Comment by Gaming12846** [comment]
IT'S A LEGIT CHEAT! Learn CODING!

**Comment by omarloler** [comment]
Are u dumb ik it is legit cheat but he can make it legit and rage cheat fucking idiot

**Comment by Gaming12846** [comment]
When you will Rage make a Pasta use Frosty Source!
Prometheus is a good Source:
https://www.unknowncheats.me/forum/cs-go-releases/275782-prometheus-source.html

**Comment by omarloler** [comment]
Ty but i got a very good source i am one taping with it
