### ISSUE TITLE
When you turn on Glow ESP, the Game crashes

### ISSUE THREAD

**Issue by XakerOrden** [smefcc/smefs-Indigo-Remastered#79]
When you turn on Glow ESP, the game simply crashes.

Windows version: 10 Pro
Injector: Public Injector
Version Indigo: 4.4.3
Video: https://youtu.be/PoX_1RYKwaA
P.S Other details are shown in the video

**Comment by smefcc** [comment]
// Glow ESP is in BETA

**Comment by XakerOrden** [comment]
@smefcc But it still does not work, I do not think it should be added to the menu if it even clumsily does not work, I think it is in the Alpha version.

**Comment by smefcc** [comment]
We just added it jessu christ. If you do not want it on the menu remove it yourself.
Its open source not everything will 100% work

**Comment by XakerOrden** [comment]
@smefcc Okay, I understand, please go to the source breathless, little pulls created
