### ISSUE TITLE
question about skinchanger

### ISSUE THREAD

**Issue by didisko33** [smefcc/smefs-Indigo-Remastered#80]
is skinchanger detected?

**Comment by XakerOrden** [comment]
I need to check, but I saw the notices in the code "This cheat (like pretty much any other pastes out there) uses Virtual Method Table (VMT) hooking, which is now detected by Valve Anti-Cheat".

**Comment by didisko33** [comment]
@XakerOrden how to determine whether the paste uses this method?

**Comment by didisko33** [comment]
@XakerOrden  ок , напишу по русски: как определить,чит будет юзать вмт хукинг или нет? в сурсе можно же как то найти ?

**Comment by XakerOrden** [comment]
@didisko33 Честно говоря я даже не знаю что это за метод и где он используется, но в Skin.cpp это уведомление висит, возможно исходники полностью детектед.

**Comment by thyanie** [comment]
Invalid.
