### ISSUE TITLE
indigo

### ISSUE THREAD

**Issue by omarloler** [smefcc/smefs-Indigo-Remastered#81]
It is safe to use indigo after the new update its so important because i am playing with my friends and i dont want to get ban

**Comment by thyanie** [comment]
Invalid issue.

**Comment by XakerOrden** [comment]
@thyanie He asked if he could play with cheats after the update (4.3.2 and 4.4.3) and if he would get a VAC ban.

**Comment by omarloler** [comment]
@XakerOrden yes that what i mean
