### ISSUE TITLE
Can you fix the RADAR?

### ISSUE THREAD

**Issue by Jeimy041** [smefcc/smefs-Indigo-Remastered#86]
I would appreciate it a lot thx btw keep on the good work!!!

**Comment by Jozkah** [comment]
What do you mean , with " fix the radar "

**Comment by Jeimy041** [comment]
Make it work again, at least mine doesn´t pop up

**Comment by Jozkah** [comment]
We change it to Engine radar only. At least it was like in 4.3 i guess

**Comment by Jeimy041** [comment]
And why is it not working

**Comment by Jeimy041** [comment]
Or how do I make it work because on my minimap isn't appearing anything
