### ISSUE TITLE
Trampoline Hooking

### ISSUE THREAD

**Issue by XakerOrden** [smefcc/smefs-Indigo-Remastered#89]
Honestly, I do not understand this, I did not even understand anything there, if I knew English, I probably would have done everything myself.
I hope you understand this: https://pastebin.com/Krn8dZaW

**Comment by smefcc** [comment]
Pretty bad way of hooking. VMT is working fine for me. I'm yet to be banned

**Comment by XakerOrden** [comment]
So VMT is detected by Valve Anti-Cheat, it turns out that your cheat is absolutely useless ?, then it is better to do it for HVH.

**Comment by smefcc** [comment]
It's a public source. Even then where's proof of VMT being detected I'm using this cheat just fine

**Comment by XakerOrden** [comment]
@smefcc I understand, I heard that you can protect the VMT of hooking, or the cheat will never be undetected?

**Comment by Enclusion** [comment]
@smefcc so you are still not banned using this hooking method?
