### ISSUE TITLE
Add Backtrack Ghost

### ISSUE THREAD

**Issue by Enclusion** [smefcc/smefs-Indigo-Remastered#95]
Makes it easier to see where the backtrack is than a line.

**Comment by smefcc** [comment]
Due to FPS issues this will **most** **likely** **not** be inplemented. And if it does it'll only be last tick or something.

**Comment by XakerOrden** [comment]
@smefcc You can just write "This function consumes a lot of computer resources", and the one who will need to be activated, + I personally really liked the idea.

**Comment by Enclusion** [comment]
@smefcc he meant that you could have a tooltip warning high resource usage.
