### ISSUE TITLE
I found another hooking method that is undetected now

### ISSUE THREAD

**Issue by Jeimy041** [smefcc/smefs-Indigo-Remastered#99]
https://www.unknowncheats.me/forum/counterstrike-global-offensive/282202-bypassing-hook-detection-4.html

https://www.unknowncheats.me/forum/c-and-c-/73824-vectored-exception-handling-hook-class.html

Maybe you guys can change your cheat and implement this one

**Comment by XakerOrden** [comment]
+ Good

**Comment by smefcc** [comment]
+ Keeping Updated Indigo VMT private until someone else releases it!
